services:

  postgres:
    image: postgres:15
    container_name: postgres_bd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data:/data

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse_bd
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - ALLOW_EMPTY_PASSWORD=yes

  spark:
    image: apache/spark:3.4.1
    container_name: spark_bd
    volumes:
      - ./spark/jobs:/opt/jobs
      - ./spark/jars:/opt/jars
      - ./spark/conf:/opt/spark/conf
    depends_on:
      - postgres
      - clickhouse
    environment:
      - SPARK_DRIVER_MEMORY=1g
      - SPARK_EXECUTOR_MEMORY=1g
      - SPARK_EXECUTOR_CORES=1
      - PYSPARK_PYTHON=python3
    command: tail -f /dev/null